#pragma once
#define MIOS_MOUSE_BUTTON_1         0
#define MIOS_MOUSE_BUTTON_2         1
#define MIOS_MOUSE_BUTTON_3         2
#define MIOS_MOUSE_BUTTON_4         3
#define MIOS_MOUSE_BUTTON_5         4
#define MIOS_MOUSE_BUTTON_6         5
#define MIOS_MOUSE_BUTTON_7         6
#define MIOS_MOUSE_BUTTON_8         7
#define MIOS_MOUSE_BUTTON_LAST      MIOS_MOUSE_BUTTON_8
#define MIOS_MOUSE_BUTTON_LEFT      MIOS_MOUSE_BUTTON_1
#define MIOS_MOUSE_BUTTON_RIGHT     MIOS_MOUSE_BUTTON_2
#define MIOS_MOUSE_BUTTON_MIDDLE    MIOS_MOUSE_BUTTON_3